# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.dgumbel <- function(x, location, scale, log_dens) {
    .Call('_dgumbel_dgumbel', PACKAGE = 'dgumbel', x, location, scale, log_dens)
}

.ddgumbel <- function(x, location, scale, log_dens) {
    .Call('_dgumbel_ddgumbel', PACKAGE = 'dgumbel', x, location, scale, log_dens)
}

.pgumbel <- function(q, location, scale, lower_tail, log_p) {
    .Call('_dgumbel_pgumbel', PACKAGE = 'dgumbel', q, location, scale, lower_tail, log_p)
}

.dpgumbel <- function(q, location, scale, lower_tail, log_p) {
    .Call('_dgumbel_dpgumbel', PACKAGE = 'dgumbel', q, location, scale, lower_tail, log_p)
}

