# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adept_eigen_test <- function(x, y) {
    .Call('_dgumbel_adept_eigen_test', PACKAGE = 'dgumbel', x, y)
}

